### ISSUE TITLE
Is there a newer documentation since ptvsd is depericated

### ISSUE THREAD

**Issue by tkumark** [awsdocs/aws-sam-developer-guide#106]
Since ptvsd is depericated for debugpy is there any new documentation for this?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
