### ISSUE TITLE
Issues With Installation Instructions: CodeBuild, --user flag, LinuxBrew

### ISSUE THREAD

**Issue by jkodroff** [awsdocs/aws-sam-developer-guide#11]
I think the installation instructions can be significantly simplified if the `--user` option is removed from the PIP installation instructions:

1. When installing on a dev machine, it's unlikely that allowing multiple versions of SAM side-by-side would be helpful.
1. When attempting to set up a CodeBuild `buildspec.yml`, the `--user` flag is downright harmful because it installs the `sam` executable to a location not in `PATH` and it is not especially clear how to get it in `PATH`.  Also, in a build container, there would be no reason to use the `--user` flag anyway.

I feel more strongly about the second point than the first as it cost me several hours in trying to set up an all-AWS-tools pipeline for a serverless project.

It's also worth noting that, probably because CodeBuild container commands run as root, the setup script for LinuxBrew fails.  Considering that LinuxBrew brings down Ruby as a dependency, I'm unsure whether this really should be the preferred option.  I assume this choice was made so as not to require writing separate sets of instructions for `apt-get` and `yum`, or, alternatively, because SAM does not publish packages for these package managers.  I think SAM should publish these packages if it does not already.

This is a working minimal configuration for a CodeBuild container.  I'll be happy to add this if someone tells me where it would belong:

```yaml
version: 0.2
phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
```

**Comment by jkodroff** [comment]
@sanathkr, thought you might also be interested in my feedback above.

**Comment by sanathkr** [comment]
Thanks for sharing feedback. It makes sense. The --user flag was primarily to prevent needing `sudo` on dev workstations. 

We want to publish to apt-get, yum etc but don't yet have it implemented. If you know how or have scripts for it, please do send a PR. It would be a great addition.

I am going to move this issue to SAM CLI repo because that is where it belongs.

**Comment by sanathkr** [comment]
@mark-hirayama Can you move this Issue to SAM CLI repo?

**Comment by jkodroff** [comment]
@sanathkr Thanks for the rapid response!  The main issue for me was struggling to get CodeBuild working.  I'd love for AWS to take a closer look at making sure there's a well-written, single source of docs on using SAM with CodeSuite because it's... well... all AWS' tooling. ;)

Happy to contribute feedback from this project both as I go along and at the end.

I am woefully ignorant of authoring packages, but I don't think it would take too long to learn based off a solid example: https://github.com/jen20/hashidays-nyc/tree/master/packaging/deb-vault

Packages should also include something for Windows using Chocolatey: https://chocolatey.org

I can say firsthand that Chocolatey packages are easy to write, especially if you're familar with NuGet (.NET's packaging system) as they use the same format.

**Comment by sanathkr** [comment]
💯Thanks for the doc feedback. 

Thanks for the examples. We have a MSI installer for Windows, but chocolatey will be good to add. 

Have you written chocolatey packages before? Can it vend Python tools thru Chocolatey?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
