### ISSUE TITLE
Outdated `sam deploy` documentation on capabilities

### ISSUE THREAD

**Issue by celkins** [awsdocs/aws-sam-developer-guide#131]
The documentation on the `--capabilities` option in `doc_source/sam-cli-command-reference-sam-deploy.md` includes the following:
> The only valid values are CAPABILITY_IAM and CAPABILITY_NAMED_IAM.

This section was apparently written before nested applications were supported and should be updated to reflect at least `CAPABILITY_AUTO_EXPAND` as described in `doc_source/serverless-sam-template-nested-applications.md`.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
