### ISSUE TITLE
Missing `FunctionResponseTypes` for events

### ISSUE THREAD

**Issue by mkamioner** [awsdocs/aws-sam-developer-guide#148]
The SQS event and stream events are missing `FunctionResponseTypes` as declared in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-functionresponsetypes.

This is a big bug since I did not know I had to declare it. Little did I know that returning the JSON response actually did not tell SQS to retry the message :-(

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
