### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by ibadsiddiqui** [awsdocs/aws-sam-developer-guide#149]
In SAM docs, the SAM CLI version needs to be updated. Currently, it is showing the old version in the doc as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/16741599/163388983-f359c98f-23bc-4152-94d4-975606b0da76.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
