### ISSUE TITLE
Error: Running AWS SAM projects locally requires Docker. Have you got it installed and running?

### ISSUE THREAD

**Issue by kmohanarangam** [awsdocs/aws-sam-developer-guide#158]
Running locally throws error saying Docker is missing. I have docker installed. 

OS: Mac - Monterey 12.4 21F79
Docker : Docker version 20.10.14, build a224086
Python: Python 3.8.9

**Error:**
```
 % sam local invoke "HelloWorldFunction" -e events/event.json
Error: Running AWS SAM projects locally requires Docker. Have you got it installed and running?
```

```
sudo sam local start-api --region eu-east-1               
Error: Running AWS SAM projects locally requires Docker. Have you got it installed and running?
```

**Comment by utibeng** [comment]
I am facing the same issue. Has anyone resolved it

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
