### ISSUE TITLE
Environment Variable Examples

### ISSUE THREAD

**Issue by rhboyd** [awsdocs/aws-sam-developer-guide#17]
The page that specifies which flags to use for sam local invoke should link to examples for the json files

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
