### ISSUE TITLE
StepFunctionsExecutionPolicy_v2 is missing in the documentation

### ISSUE THREAD

**Issue by thomasfr** [awsdocs/aws-sam-developer-guide#183]
On the SAM Policy Templates documentation page (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html) the `StepFunctionsExecutionPolicy_v2` Policy is missing.
The [policy\_templates\.json](https://github.com/aws/serverless-application-model/blob/develop/samtranslator/policy_templates_data/policy_templates.json) does contain it though.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
