### ISSUE TITLE
Add to guided flag behavior in "sam deploy" documentation

### ISSUE THREAD

**Issue by awsdiegorad** [awsdocs/aws-sam-developer-guide#186]
Currently, when using the --guided flag when running "sam deploy", SAM will automatically create a CloudFormation stack named "aws-sam-cli-managed-default-samclisourcebucket" if it has not already been created on the target environment. The creation of this stack is not clearly mentioned in the documentation for "sam deploy". 

Related Doc: 
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html

Related Issues:
https://github.com/awsdocs/aws-sam-developer-guide/issues/95

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
