### ISSUE TITLE
Add Docker file sharing issues on Windows to Troubleshooting guide

### ISSUE THREAD

**Issue by sanathkr** [awsdocs/aws-sam-developer-guide#24]
Someone tried the getting started guide but ran into a strange error. Root of errors like this is that the local file system is not shared with Docker. Unfortunately Docker does not fail but instead just continues to work. We should add a troubleshooting section to getting started guide to detect such issues and enable file sharing.

https://github.com/awslabs/aws-sam-cli/issues/1345

**Comment by zwkf** [comment]
I agree

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
