### ISSUE TITLE
Issue with S3 bucket creation after aws configure step

### ISSUE THREAD

**Issue by nathankc** [awsdocs/aws-sam-developer-guide#26]
When a user has copy / pasted the access / secret key credentials from .csv and performs the S3 bucket creation setp, aws cli make_bucket can fail with "SignatureDoesNotMatch" error (
"The request signature we calculated does not match the signature'")
(similar to: https://github.com/aws/aws-cli/issues/602)

Step should recommend copy / paste directly from browser for the aws configure step

aws-cli/1.16.238 Python/3.6.0 Windows/10 botocore/1.12.228

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
