### ISSUE TITLE
Mention alternative install method using pip for sam-cli on Linux

### ISSUE THREAD

**Issue by mbacchi** [awsdocs/aws-sam-developer-guide#29]
Most Linux users don't use Brew, as the OS already has a package manager. Python pip is an alternative method for installing `sam-cli` but the [documentation](https://github.com/awsdocs/aws-sam-developer-guide/blob/master/doc_source/serverless-sam-cli-install-linux.md) indicates Brew as the only option.

I'll leave my opinion of Brew out of this issue, but the documentation should reference all possible methods of installing the client.

**Comment by mendhak** [comment]
Hello. Please AWS, would appreciate this being given some attention. 🙏 

The Linux ecosystem and developers make use of several robust and well known package managers.  
Brew for Linux is an afterthought and extremely uncommon; further, this is a drastic and important change to the user's environment which can affect a lot more than just their development environment.

> This step causes your environment's default Python version to be the one installed by Homebrew. 

It would be great if the `pip` instructions could replace the brew instructions on the setup page.  

For reference, [the issue on aws-sam-cli](https://github.com/awslabs/aws-sam-cli/issues/1424#issuecomment-542644819) is also open.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
