### ISSUE TITLE
Add Models example

### ISSUE THREAD

**Issue by dre2004** [awsdocs/aws-sam-developer-guide#39]
I'm looking for some sample code on how to use a Model within a SAM template, according to the template there is supposed to be an example of how to use models.

>  Models

    The schemas to be used by your API methods. These schemas can be described using JSON or YAML. See the Examples section at the bottom of this page for example models. 

But there is no example to be found.

**Comment by robotkala** [comment]
I support this as having problems creating models

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
