### ISSUE TITLE
HttpApi tags conditions

### ISSUE THREAD

**Issue by farski** [awsdocs/aws-sam-developer-guide#51]
The [docs] for `HttpApi` currently say: 

> Because Tags requires AWS SAM to modify your OpenAPI definition, they will only be added if the DefinitionBody property is specified—no tags will be added if the DefinitionUri property is provided.

This isn't entirely accurate, or at least not obviously so. Tags will also be added if _neither_ `DefinitionBody` nor `DefinitionUri` are provided, and the entire definition is inferred from other SAM resources.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
