### ISSUE TITLE
Is JSON a valid syntax for SAM templates?

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-sam-developer-guide#60]
On this file:

https://github.com/awsdocs/aws-sam-developer-guide/blob/master/doc_source/serverless-sam-cli-using-validate.md

it says:

> Validate your templates with [sam validate](sam-cli-command-reference-sam-validate.md). Currently, this command validates that the template provided is valid JSON / YAML. 

Is JSON a valid syntax for SAM templates?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
