### ISSUE TITLE
Update the samcli install guide to use pip3 for installation as well

### ISSUE THREAD

**Issue by kunalsumbly** [awsdocs/aws-sam-developer-guide#74]
I struggled to install homebrew on my EC2 Ubuntu Server 18.04 LTS (HVM) as mentioned in the official documentation as the following particular command
**brew install aws-sam-cli** , kept on giving different kinds of errors, and then I found after some googling that even pip can be used to install sam-cli and I finally used pip to install the sam-cli on my box. I think it would be better to update the documentation https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html 
to include the installation steps using pip3 as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
