### ISSUE TITLE
Incorrect link in AWS::Serverless::Function

### ISSUE THREAD

**Issue by campj90** [awsdocs/aws-sam-developer-guide#79]
The 'Deploying Serverless Applications Gradually' link under the AutoPublishCodeSha256 property points to the Portuguese/Brazilian documentation page. Not a huge deal, just kind of amusing, and thought you should be aware of it.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
