### ISSUE TITLE
Tutorial does not inform that the environment variables NEED to be in the template file

### ISSUE THREAD

**Issue by MikaelBrenner** [awsdocs/aws-sam-developer-guide#83]
While the tutorial states the format of the file
```
{
  "MyFunction1": {
    "TABLE_NAME": "localtable",
    "BUCKET_NAME": "testBucket"
  },
  "MyFunction2": {
    "TABLE_NAME": "localtable",
    "STAGE": "dev"
  }
}
```
And the usage of the file:
`sam local invoke --env-vars env.json`

It will not work unless the variables are defined on your template file, like:
```
MyFunction1:
    ...
    Properties:
    ...
    Environment:
        Variables:
          TABLE_NAME: tab
          BUCKET_NAME: test
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
