### ISSUE TITLE
Clarify samconfig.toml header keys

### ISSUE THREAD

**Issue by mousedownmike** [awsdocs/aws-sam-developer-guide#89]
### Describe your idea/feature/enhancement

The [AWS SAM CLI configuration file](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html) documentation does not provide enough information to properly format a `samconfig.toml` file when a subcommand contains hyphens (`-`).

The relevant documentation is:

>For subcommands, the format of the table header is [_environment.command_subcommand.parameters_]. For example, for the `sam local invoke` command, the configuration table header is [default.local_invoke.parameters].

### Proposal

Add a section to read:

>Hyphenated subcommands must have hyphens converted to underscores. For example, for the `sam local start-api` command, the configuration table header is [default.local_start_api.parameters].

### Additional Details

It's possible that this is something most people know about the `TOML` format but it is difficult to figure out and remember the conversions between JSON, YAML and TOML.  

Originally from: https://github.com/aws/aws-sam-cli/issues/2378

**Comment by mark-hirayama** [comment]
This issue was addressed with an update to the docs.
