### ISSUE TITLE
Animations don't translate to Kindle

### ISSUE THREAD

**Issue by mousedownmike** [awsdocs/aws-sam-developer-guide#92]
The documentation in the "Testing and debugging" section reference animated GIF files of a VS Code interaction.  When viewed in the Kindle version of the guide, the images are static and the context is lost.  From my perspective, the animations don't provide much value and may belong in a section specific to VS Code.   

The pages are:
* [Invoking Functions Locally](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html)
* [Running API Gateway locally](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
