### ISSUE TITLE
--s3-* options ignored with sam deploy --guided

### ISSUE THREAD

**Issue by mousedownmike** [awsdocs/aws-sam-developer-guide#95]
Per this issue: https://github.com/aws/aws-sam-cli/issues/1700

The `--s3-*` options appear to be ignored when used with `--guided`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
